### ISSUE TITLE
Nerdbank.GitVersioning

### ISSUE THREAD

**Issue by AArnott** [dotnet-foundation/projects#28] opened 2019-11-18 20:40 UTC
## 1.   General Information

**Project Name:** Nerdbank.GitVersioning

**License:** MIT

**Contributor (Company, Organization or individual name(s)):** Andrew Arnott

**Existing OSS Project? (Yes/No):** Yes

**Source Code URL:** https://github.com/AArnott/Nerdbank.GitVersioning/

**Project Homepage URL (if different):**

**Project Transfer Signatories:**
Full legal name and email address required of the individual(s) with the authority to transfer or contribute the project to the .NET Foundation. Note that if you'd prefer not to include this in the public application, it can be submitted via e-mail to contact@dotnetfoundation.org (referencing this issue number).

Andrew Arnott \<andrewarnott@gmail.com\>
[Andreas Gruenwald](https://github.com/AArnott/Nerdbank.GitVersioning/commits?author=ap0llo) \<andreasgruenwald@live.de\>

## 2.   Description

Stamp your assemblies, packages and more with a unique version generated from a single, simple version.json file and include git commit IDs for non-official builds.

**Please provide a 1 sentence (<140 character) summary of your to help users when searching the .NET Foundation projects**

Build unique versions of your projects based on git commits automatically.

## 3.   Project Governance

**Project Lead:**

Name:   Andrew Arnott
 Email:   andrewarnott@gmail.com
 GitHub Profile URL:  https://github.com/aarnott

**Committers:**

Which individuals have commit / write access to the repository, what is their GitHub ID and who is their employer (if contributions are on behalf of an employer)

We have 37 contributors, but no one else has push permissions.

**Governance Model:**

Benevolent dictator

Issues typically precede pull requests, which is good because some ideas from the community need refinement before codifying to avoid wasted effort.
Whether started by PR or issue, each one gets initial attention and review. Most bug reports, fixes or features are likely to be granted as time permits. 

There is a particular set of features that are summarily denied when requested because they go against a core principle of this project, which is that for any git commit, you can only build either of a pair of versions: public or private. 

**CLA**

If already an OSS project, was a Contribution License Agreement in place for contributions accepted? How does the project check who has signed one?

We do not have a CLA process in place.

**CLA Notification Alias**

andrewarnott@gmail.com

**Project Transfer Type**

Projects may join the .NET Foundation in one of two ways and you should chat with your .NET Foundation contact to discuss the best mechanism for your project. You can either a) assign the copyright of the project's source code to the .NET Foundation or b) contribute the project source code to the .NET Foundation under an open source license. Assignment is the preferred approach, but licensing a project to the Foundation may be more appropriate for longer running open source projects that have not previously had a contribution license agreement and have accepted contributions from many different sources.
a) Assignment
**b) Contribution**

## 4.   Repository Layout
The .NET Foundation host guidance for new projects and details on recommended structure here:
[https://github.com/dotnet/home/tree/master/guidance](https://github.com/dotnet/home/tree/master/guidance)

Note that the open source repository should be the master where changes are made by the core development team using the same PR process that is used for non-committer contributions.

Please define below any changes you would want to make to your repositories as part of the process of joining the .NET Foundation

[ ] Reorder top two lines in our LICENSE file to match guidance.
[ ] Add NOTICE.txt file with attribution to libgit2sharp, libgit2 projects which get embedded into this repo's binary packages.

## 5.   PR Plan

No big announcement is planned. I expect we'll just add a notice in the README when it's final.

## 6.   Infrastructure Requirements

The repo is built and deployed by Azure Pipelines via git-tracked YAML files that define the build. 
We may eventually switch to GitHub Actions v2.

I would appreciate authenticode signing certs that we can use for official builds.

## 7.   Additional Notes

A similar project in this space is [GitVersion](https://github.com/gittools/gitversion). GitVersion takes a different principled approach of allowing all sorts of computed versions for a given commit based on its context (e.g. local vs. cloud build, branch name, PR build status, etc.). 
Nerdbank.GitVersioning prioritizes reproducible builds over nearly all else so that a build locally on a dev box will produce the exactly the same result in a cloud build. It is also much easier to set up as it automatically integrates into nearly all the environments/projects it supports.

## 8. Checklist

Title: On-Board project to the .NET Foundation

We're getting ready to bring the project into the .NET Foundation, but before we
do we need to do the following:

## Getting into the .NET Foundation
- [x] Make sure the project has a good name that is easy to remember and 
 spell. Check that it doesn't [conflict with another existing project](http://ivantomic.com/projects/ospnc/)
- [x] Make sure the people involved in the project want to join the .NET Foundation
- [ ] Make sure the project has a clear understanding about how it accepts contributions and the process
     it follows when selecting new committers to the project.
- [x] [Register an interest](https://dotnetfoundation.org/get-involved) in joining the .NET Foundation
- [x] Work with the .NET Foundation to fill out an On-Boarding Questionaire
- [x] .NET Foundation sends out completed questionaire to .NET Foundation Advisory Council for comments
- [x] .NET Foundation Executive Director submits new project proposal to the .NET Foundation Board
- [ ] Configure a CI build for the project and ensure build status badges are available from the README

## Once accepted into the .NET Foundation
- [ ] Sign the contribution / assignment agreement
- [ ] Agree a date to move into the .NET Foundation
- [ ] Prepare a guest blog post announcing the move on the .NET Foundation Blog
- [ ] Read the [code of conduct](https://dotnetfoundation.org/code-of-conduct), 
      [link to it in your code](be-nice.md) and 
      understand what to do if you are concerned about any behaviour or have
      concerns reported to you.
- [ ] Tell the world we have joined!
- [ ] Get CLA Automation enabled to ensure contributors can easily sign the 
      [Contribution License Agreement](https://github.com/dotnet/home/blob/master/guidance/net-foundation-contribution-license-agreement.pdf)
- [ ] Send a PR to add the Project into the .NET Foundation 
      [list](https://github.com/dotnet/home/tree/master/projects)
- [ ] Ensure the repo contents are up to date with [.NET Foundation guidance](https://github.com/dotnet/home/blob/master/guidance/repo-guide.md)
- [ ] Review the [README guidance](readme-guide.md) and update if necessary
- [ ] If applicable [update the LICENSE file](copyright.md) to show Copyright has been assigned to the .NET Foundation
      and look to update any file headers.
- [ ] If applicable, update any copyright statements in websites owned by the project to reflect 
      assignment to the .NET Foundation
- [ ] If applicable, update any websites associated with the project to include
      "Supported by the <a href="https://dotnetfoundation.org">.NET Foundation</a>" or
      similar link back to the .NET Foundation in the footer. If applicable, please
      include image links from [our swag repo](https://github.com/dotnet/swag). (We think a link in the footer using the horizontal logo looks very nice.)
- [ ] [Sign up for Project Leader news](http://eepurl.com/bOCfJP)
- [ ] Configure any resources requested from the .NET Foundation (SSL Certs, Code Signing,
      Secret Management, Build Servers etc)

**Comment by AArnott** [comment] 2019-11-18 20:41
@ap0llo as a contributor of the `nbgv prepare-release` command (making yourself the largest contributor besides myself to this project), can you assert your approval for NB.GV's inclusion in the .NET Foundation?

**Comment by ap0llo** [comment] 2019-11-18 20:51
Yes, of course. I approve. 👍

**Comment by onovotny** [comment] 2019-11-22 15:43
I don't think this was intended on being closed.

**Comment by AArnott** [comment] 2020-01-10 20:06
@jongalloway Now that this is accepted, what is the next step?

**Comment by jongalloway** [comment] 2020-01-16 21:34
Onboarding agreement sent via DocuSign

**Comment by AArnott** [comment] 2020-01-21 19:26
Signed.

**Comment by ChrisSfanos** [comment] 2020-03-05 21:05
CLA is completed - moving to CLA onboarding in GitHub

**Comment by ChrisSfanos** [comment] 2020-03-06 16:27
We will track the remaining onboarding work via this checklist:

## Onboarding
- [ ] CLA Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Post Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Enable CLA automation for future contributors
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)

**Comment by ChrisSfanos** [comment] 2020-03-09 14:26
Per @AArnott , all steps are done

**Comment by ChrisSfanos** [comment] 2020-03-09 14:37
Closing

**Closed by ChrisSfanos** 2020-03-09 14:37 UTC
Labels: project application
